### ISSUE TITLE
setup_linux & Archlinux

### ISSUE THREAD

**Issue by polgiron** [Iotic-Labs/demo#4]
The route commands in the setup_linux file don't work in an Archlinux environment.
I have errors like "invalid options".

However this command is working:
sudo route add -net 224.0.0.0 netmask 224.0.0.0 dev lo

uname -r: 3.19.2-1-ARCH

edit: apparently it's the same on the raspberry pi with raspbian

**Comment by whaleygeek** [comment]
The instructions for route configuration are indeed a bit wrong, and they do vary between platforms. It has always been my intention to eventually hide all the kernel configuration and platform variances inside the netcast.py file and get it to set up kernel routes automatically. That might happen one day - in the meantime use "man route" on your platform to work out how to configure your platform.

Basically, there needs to be a multicast route for 224.0.0.0 (all multicast), or at least the multicast address you are using in your script, as a minimum. To allow points to follow each other from different processes on the same platform you need a multicast route for interface "lo". To use over ethernet you will need eth0 or eth1 depending on your platform, and for wireless routes you will need wlan0 or equivalent.

The best place to start is to type 'ifconfig' on linux/mac (ipconfig on windows) to see what interfaces are available, and then use the 'route' command appropriate for your platform to set up these multicast routes. Once set, they don't need to be set again until reboot.

The underlying netcast.py uses multicasting in order to achieve a no-server setup (everything is distributed and no one node is master in this sandbox, meaning you should be able to plug in an arbitrary set of SD cards into an arbitrary set of raspberry pi computers, boot them, download the zip, run it and it should just work (once multicast configured of course).

**Comment by whaleygeek** [comment]
This is fixed in the latest release.
